### ISSUE TITLE
Infografía de las librerías - Diego Alexis Carlos Cruz

### ISSUE THREAD

**Issue by g00gle2401** [SistemasTecTlaxiaco/infografia-de-las-librerias-g00gle2401#2]
[Libreria&Practica - DiegoAlexisCarlosCruz4US.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-g00gle2401/files/8823816/Libreria.Practica.-.DiegoAlexisCarlosCruz4US.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion...

**Comment by Arnold-Js** [comment]
Calificacion de Diego 19 de 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
