### ISSUE TITLE
InfografíaDeLibrerias-DiegoAlexisCarlosCruz

### ISSUE THREAD

**Issue by g00gle2401** [SistemasTecTlaxiaco/infografia-de-las-librerias-g00gle2401#3]
[Libreria&Practica - DiegoAlexisCarlosCruz4US.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-g00gle2401/files/8346539/Libreria.Practica.-.DiegoAlexisCarlosCruz4US.pdf)

**Comment by Sandra631** [comment]
20% Bien hecho

**Comment by josealfredo79** [comment]
bien hecho y revisado...
